experiment_name: gpt3_two_layers_logprobs
fwd_model: text-davinci-003
sco_model: text-davinci-003
bwd_model: text-davinci-003
do_train: true
num_prompts: 5
num_hiddens: 5
num_epochs: 25
bwd_temp: 1.0
num_train_examples: 10
batch_size: 10
eval_freq: 2
fwd_max_tokens: 512
bwd_max_tokens: 512
skip_first_test_accuracy: True
dataset: navigate
data_path: ../../data/bbh
layers_initialization:
  - layer_index: 0
    template_type: suffix
    initial_instruction: ""
    output_formatting_instruction: "Let's think step by step."
  - layer_index: 1
    template_type: prefix
    initial_instruction: Read the following sentence, choose whether you return to the starting point.
    output_formatting_instruction: Now generate the output, which should be either 'yes' or 'no'.
    output_classes: ["yes|Yes", "no|No"]
