- name: gpt-3-fwd
  model: text-davinci-003
  api_key: ${OPENAI_API_KEY}
  api_base: ${OPENAI_API_BASE}
  api_type: ${OPENAI_API_TYPE}
  api_version: ${OPENAI_API_VERSION}
  temperature: 0.0
  max_tokens: 512

- name: gpt-3-bwd
  model: text-davinci-003
  api_key: ${OPENAI_API_KEY}
  api_base: ${OPENAI_API_BASE}
  api_type: ${OPENAI_API_TYPE}
  api_version: ${OPENAI_API_VERSION}
  temperature: 0.7
  max_tokens: 512

# - name: llama2-fwd
#   model: /data/llama2/70Bf
#   api_key: EMPTY
#   api_base: http://127.0.0.1:8000/v1
#   api_type: null
#   api_version: null
#   max_tokens: 256
#   temperature: 0
