name: "Run"

on:
  push:
    branches: [ "e2e_tests", "main"]
  schedule:
    - cron: '0 3 * * *'

env:
  OPENAI_API_KEY: ${{ secrets.VLLM_API_KEY }}
  OPENAI_BASE_URL: ${{ secrets.VLLM_BASE_URL }}
  
jobs:
  tests:
    name: Run
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [ "python" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[dev]'
          bash scripts/setup_data.sh
      - name: Run experiments
        run: |
          cd projects/vi_dln
          output=$(python vi_main.py \
          --iters 0 \
          --dataset navigate \
          --fwd_model_type microsoft/phi-2 \
          --bwd_model_type microsoft/phi-2)
          echo "$output"
          if echo "$output" | grep -q "TEST ACC: 0.608"; then
            echo "Output check passed"
          else
            echo "Output check failed"
            exit 1
          fi