name: "Run"

on:
  push:
    branches: [ "flask" ]
  schedule:
    - cron: '* * * * 5'

env:
  OPENAI_BASE_URL: http://127.0.0.1:5000/v1
  
jobs:
  tests:
    name: Run
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [ "python" ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[dev]'
          bash scripts/setup_data.sh
      - name: Start flask server
        run: |
          flask --app flask/app.py run &
          sleep 60s
          curl http://127.0.0.1:5000/v1/completions -v -H "Content-Type: application/json" -H "Authorization: Bearer $OPENAI_API_KEY" --data "{\"model\":\"alpaca-lora-7b\",\"prompt\":\"Where is New York?\",\"max_tokens\":7,\"temperature\":0}"
      - name: Run experiments
        run: |
          cd projects/vi_dln
          bash scripts/two_layers_e2e/phi2_phi2_DLN-2.sh